### PR TITLE
Topology updates

### PR DESCRIPTION
**Pull request by italobusi**
The OTN topology at MPI1 (mpi1-otn-topology.json) has been updated as discussed in previous DT call:
- I2RS and TE topology identifiers are aligned with pull request #10
- the abstact nodes and links have been updated in line with the comments in pull request #15

### CODE REVIEW

**Comment by italobusi** [comment]
Additional items for further discussion:
- should we add label-restriction? under discussion via e-mail
- add otn bandwidth information: #50
- discuss feedbacks with TE topology authors: #51
  - duplicated information of interface-switching-capability in LTP and Link
  - link-protection-type: can we assume unprotected as the default value?
  - access-type: can we assume point-to-point as the default value?

**Comment by GianmarcoBruno** [comment]
Hi all
[here](https://github.com/GianmarcoBruno/transport-nbi-backoffice/blob/master/use-case-1-topology-data/mpi1-otn-topology.json) you can find the otn-topology.json example fixed and trimmed to 68 chars.
I started from the version committed by Italo [see here](https://github.com/danielkinguk/transport-nbi/pull/44/commits/6136ae75a651315b6cfc21a6a6e45d31e29d5bdd) after our October 10 meeting.

**Comment by GianmarcoBruno** [comment]
Sorry I closed by mistake the pull request. Of course I'm still waiting for the reviews.

**Comment by sergiobelotti** [comment]
I put comments here since it seems review does not work properly.
NODE description: it seems only admin-status appers on json plus oper-status for derived state. No other nodes attributes are shown. Is it correct ?

**Comment by italobusi** [comment]
DT call on October 17, 2018

Ok not to add label restrictions to simplify the JSON code

Add some notes to clarify to the reader the objects that have not been included in the JSON example (to be completed in the next update)

**Comment by italobusi** [comment]
**DT call on October 17. 2018**

Reviewed the link attributes in the JSON code examples and identfied one new actions:
- discuss with TE Topology authors the use of the is-abstract attribute and of the underlay containers

**Comment by carloperocchio** [comment]
I agree with proposed contents.
I suggest to add pictures for 4.2 containing network described in wording and, consistently, for 5.1.1

**Comment by GianmarcoBruno** [comment]
Hi
attached you can find the latest JSON unfolded and valid and the folded version using the tool in https://tools.ietf.org/html/draft-kwatsen-netmod-artwork-folding-08


[mpi1-otn-topology.zip](https://github.com/danielkinguk/transport-nbi/files/2493285/mpi1-otn-topology.zip)

**Comment by GianmarcoBruno** [comment]
Perhaps it's better to leave it open until the merge is done

**Comment by GianmarcoBruno** [comment]
Hi wait a bit before pasting the json in the I-D. I forgot to re-fetch the YANG models and validate the instance against them. I'll do it as soon as possible.

**Comment by GianmarcoBruno** [comment]
Attached the mpi-topology json file with updated YANG models but the OTN ones.

[mpi1-otn-topology.zip](https://github.com/danielkinguk/transport-nbi/files/2498117/mpi1-otn-topology.zip)

**Pull request merged**
