### PR TITLE
DT Review

### PR DESCRIPTION
**Pull request by italobusi**
DT review of the document prior to requesting CCAMP WG LC

Pending resolution of:
- [x] open issue #46
- [x] open issue #63 
- [x] open issue #64 
- [x]  open issue #65

### CODE REVIEW

**Comment by michael-scharf** [comment]
My review comments can be found in #67 #68 #69 #70 #71 #72.

Note that some comments are just random thoughts and it may be OK not to take them into account.

**Comment by dieterbeller** [comment]
Please find in the attached document my proposed changes and comments up to section 4.1.
I will continue reviewing the remaining sections.

[draft-ietf-ccamp-transport-nbi-app-statement_DB_part_1.docx](https://github.com/danielkinguk/transport-nbi/files/3320836/draft-ietf-ccamp-transport-nbi-app-statement_DB_part_1.docx)

**Comment by haomianzheng** [comment]
Please find in the attached document about my comments. Most of them have been addressed in the call on June 24th. Will followup if any more. 
[draft-ietf-ccamp-transport-nbi-app-statement-haomian.docx](https://github.com/danielkinguk/transport-nbi/files/3329993/draft-ietf-ccamp-transport-nbi-app-statement-haomian.docx)

**Comment by italobusi** [comment]
Proposed text updates for discussion during the July 31, 2019 DT call:

[draft-ietf-ccamp-transport-nbi-app-statement-ib-2019-07-30.docx](https://github.com/danielkinguk/transport-nbi/files/3447099/draft-ietf-ccamp-transport-nbi-app-statement-ib-2019-07-30.docx)

Addressing open issues: #65, #68 and #74

**Comment by italobusi** [comment]
Proposed text updates from Daniel, for discussion during the July 31, 2019 DT call:

[draft-ietf-ccamp-transport-nbi-app-statement-05-English-Review-DK-Comments.docx](https://github.com/danielkinguk/transport-nbi/files/3451228/draft-ietf-ccamp-transport-nbi-app-statement-05-English-Review-DK-Comments.docx)

Addressing open issues: #71, #73 and #75

**Comment by italobusi** [comment]
2019-07-31 DT Call

Proposed text changes from Italo and Daniel merged and reviewed

Output of the DT review uploaded, incorporating all DT review comments resolution up to July 31, 2019

ac8ddacb1ff5be98ceaf17713a2c0bbc6d2c9657: is the version with revision bars
ab9fd15817437be2d70571c2b5b8c3debf7613dd: is the clean-up copy

@danielkinguk : Please refer to the latest update in https://github.com/danielkinguk/transport-nbi/tree/dt-review/I-D%20Applicability%20Statement, wchih is aligned with ab9fd15817437be2d70571c2b5b8c3debf7613dd as the clean-up copy for your English review and Adrian's review

**Comment by italobusi** [comment]
Comments from Daniel: 
[draft-ietf-ccamp-transport-nbi-app-statement-06-English-Review-DK-Comments.docx](https://github.com/danielkinguk/transport-nbi/files/3729205/draft-ietf-ccamp-transport-nbi-app-statement-06-English-Review-DK-Comments.docx)

**Comment by michael-scharf** [comment]
Sorry, I won't have cycles to review the entire document comprehensively prior to the cutoff deadline. I briefly scanned through it. All in all, I think it looks good.

Editorial nit: PNC is defined as "Provisioning Network Controller" in RFC 8453; at least on page 4 another expansion is used

**Comment by michael-scharf** [comment]
Sorry, I won't have cycles to review the entire document comprehensively prior to the cutoff deadline. I briefly scanned through it. All in all, I think it looks good.

Editorial nit: PNC is defined as "Provisioning Network Controller" in RFC 8453; at least on page 4 another expansion is used

**Comment by italobusi** [comment]
> Sorry, I won't have cycles to review the entire document comprehensively prior to the cutoff deadline. I briefly scanned through it. All in all, I think it looks good.
> 
> Editorial nit: PNC is defined as "Provisioning Network Controller" in RFC 8453; at least on page 4 another expansion is used

Nit fixed in b5af238bbe30eadeecb0b3ec70174844251d7fc4

**Pull request merged**
