### PR TITLE
Adding automatically generated topology for UC1

### PR DESCRIPTION
**Pull request by rvilalta**

### CODE REVIEW

**Comment by italobusi** [comment]
Reviewed during the DT call on September 20

**Comment by italobusi** [comment]
@GianmarcoBruno : could you please check that the new JSON code fit into the I-D 72 characters width and it passes the YANG validation checks?

**Comment by italobusi** [comment]
@rvilalta 
Is it possible to have the identifiers at the beginning of the object?

For example:

`
    "network": [
      {
        "//": "ODU Abstract Topology @ MPI",
        "network-id": "onos",
        "network-types": {
          "ietf-te-topology:te-topology": {
            "ietf-otn-topology:otn-topology": {}
          }
        },
`

**Comment by GianmarcoBruno** [comment]
OK will do asap
Gianmarco

**Comment by italobusi** [comment]
Proposal included into pull request #4

**Pull request closed without merging**
