### PR TITLE
Merged Draft (Applicability Statement v01)

### PR DESCRIPTION
**Pull request by italobusi**
Initial proposal for a merged draft

### CODE REVIEW

**Comment by GianmarcoBruno** [comment]
I support the merging of the various texts into one and the outline shared by Italo by email.

**Comment by haomianzheng** [comment]
[tnbi-merged-draft-00-haomian.docx](https://github.com/danielkinguk/transport-nbi/files/1706506/tnbi-merged-draft-00-haomian.docx)

**Comment by XYBPHIL** [comment]
Add 4.6, to specify the process of service modification/delete. The service configuration include service creation, modification and deletion. 
For example, the service modification include the service bandwidth modification and service SLA level upgrade and degrade, such as service protection type changed form unprotection to 1+1 protection.

**Comment by XYBPHIL** [comment]
Some restoration and notification text added in section 4.5.3 and 4.6 for reference.
[merged-draft-00-xuyunbin.docx](https://github.com/danielkinguk/transport-nbi/files/1765840/merged-draft-00-xuyunbin.docx)

**Comment by italobusi** [comment]
@haomianzheng : Please check if updated version (2018-03-01) addresses your comments

**Comment by italobusi** [comment]
The initial proposal for the merged draft has been renamed with the new file name (draft-ietf-ccamp-transport-nbi-app-statement-01-20171212.docx) and moved in the new Applicability-Statement/01 folder

**Comment by italobusi** [comment]
Latest draft update (draft-ietf-ccamp-transport-nbi-app-statement-01-20171212.docx) includes:
- input material from Yang Zhao
- Sergio's comment resolutions on terminology (issue #17)
- JSON code from Gianmarco (pull request #24)
- JSON code from Ricard (pull request #15)

**Comment by ploenin** [comment]
Add 4.1.2. Multi-Domain Scenario, 4.3.6. Dynamic Service Configuration and 4.7. Path Computation with Constraint. Thanks!

**Pull request merged**
