### PR TITLE
ODU2 and EPL Service Examples

### PR DESCRIPTION
**Pull request by italobusi**
Updated JSON code examples to setup ODU2 and EPL Services @ MPI1

Actions for future updates:
- Update and validate the JSON examples for ODU2 service and tunnel with the next updated version of the TE and OTN Tunnel models (when available)
- Add the te-topology-identifier information: pending pull request #10 
- Wait for the next TE Tunnel model update to indicate it is a native bidirectional tunnel: pending open issue https://github.com/ietf-mpls-yang/te/issues/25
- Wait for the next TE Tunnel model update to move the hierarchical-link container under the tunnel: pending open issue https://github.com/ietf-mpls-yang/te/issues/30
- @italobusi : Update the REST operation to avoid replacing the whole te datastore
- @italobusi : Check with TE Tunnel model authors why the source and destination attributes are defined as ip-address and not as te-node-id
- @sergiobelotti : Check the need for the ietf-otn-tunnel:payload-treatment attribute
- @italobusi : Check with OTN Tunnel model authors if the src-tpn, src-tsg, src-tributary-slot-count, src-tributary-slots, dst-tpn, dst-tsg, dst-tributary-slot-count and dst-tributary-slots attributes/containers should be removed
- @italobusi : Check with TE Tunnel model authors how to set the te-label direction

### CODE REVIEW

**Comment by italobusi** [comment]
Actions for future updates:
- Add the te-topology-identifier information: pending pull request #10 
- Wait for the next TE Tunnel model update to indicate it is a native bidirectional tunnel: pending open issue https://github.com/ietf-mpls-yang/te/issues/25
- Wait for the next TE Tunnel model update to move the hierarchical-link container under the tunnel: pending open issue https://github.com/ietf-mpls-yang/te/issues/30

**Comment by italobusi** [comment]
**May 4, 2018:**

JSON code examples for ODU2 Tunnel and Service updated based on the feedbacks/comments discussed during the DT call on April 18, 2018

**Comment by italobusi** [comment]
@sergiobelotti : fixed in https://github.com/danielkinguk/transport-nbi/pull/29/commits/f0d086865796f7fc17c10a920968aa9901325bbc

**Comment by GianmarcoBruno** [comment]
The reviewed .json file for the topology can be found here
[https://github.com/GianmarcoBruno/transport-nbi-backoffice/blob/master/use-case-1-topology-get/mpi1-otn-topology.json]
Re. the .json for the odu2 service configuration there is mismatch between ietf-te and otn-tunnel models

**Comment by giantabasco** [comment]
The reviewed .json for the ODU2 service has been validated. Needed to downgrade the ietf-te models to make them compatible with the now expired ietf-otn-tunnel model. You can find it at:
<https://github.com/GianmarcoBruno/transport-nbi-backoffice/blob/master/use-case-1-odu2-service-post/mpi1-odu2-service-config.json> Still to be trimmed in the 72 chars.

**Comment by giantabasco** [comment]
The reviewed .json for the EPL service has been validated and trimmed. You can find it at:
<https://github.com/GianmarcoBruno/transport-nbi-backoffice/blob/master/use-case-1-epl-service-config/mpi1-epl-service-config.json>

**Comment by italobusi** [comment]
Thanks Gianarmarco

The pull request has been updated with the validated versions of the mpi1-otn-topology.json and mpi1-epl-service-config.json files:

- https://github.com/danielkinguk/transport-nbi/pull/29/commits/11eabeb952677c8cb4376fb5f17ba2681f0d9ba1
- https://github.com/danielkinguk/transport-nbi/pull/29/commits/84ddd4afee80212e4149329e49e88faef66fecb3

**Comment by italobusi** [comment]
Let's review and merge this pull request even if the examples based on the tunnel model cannot be validated

**Comment by italobusi** [comment]
@giantabasco : your comment is correct. The plan is to update the JSON code syntax for odu2-service-config and mpi1-odu2-tunnel-config in a future pull request as soon as the updated OTN YANG model is published

**Pull request merged**
